#-- TARGET definition :
TARGET_TYPE=lib#one of : exe, lib, default to exe
TARGET=libbmpfile.a
#-- libs definition :
LIBS=libft libd42_sys#list of libs (prefixed with lib : e.g libfoo) which must be recompiled by this Makefile
ft_DIR=../ft
d42_sys_DIR=../endianess
#-- srcs definition :
SRCS=bmpfile_save.c
SRCS_DIRS=
SRCS_INCS=.#
#
#---- dont change anything after this
#--------------------------------------------------------------------------------------

GEN_MAKEFILE_PATH=/home/david/42Projects/minirt/.d42Makefile
include $(GEN_MAKEFILE_PATH)/genMakefile

